### PR TITLE
Fix race condition in redis limiter

### LINKED ISSUE #162: Redis vulnerability with key expiration not being set
I ran into a vulnerability with the RedisRateLimiter class in regards to how it manages key expiration. In `calcRemaining` there's the following code block:

```
current = redisTemplate.opsForValue().increment(key, usage);
// Redis returns the value of key after the increment, check for the first increment, and the expiration time is set
if (current != null && current.equals(usage)) {
    handleExpiration(key, refreshInterval);
}
```

If `increment()` succeeds on a new entry and `handleExpiration()` fails for whatever reason, then the entry won't have an expiration, and no subsequent call into `calcRemaining` will attempt to set it since `current.equals(usage)` will be false. In which case the remaining limit will never reset, so once the limit number of calls is made, 429 will always be returned for the given key. The only way to fix it is to manually remove the key from redis. Obviously this is a major issue, since the filter will discard valid requests incorrectly.

A fix to this issue could look something like this:

```
boolean success = redisTemplate.opsForValue().setIfAbsent(key, usage, refreshInterval);
if(!success)
{
   // Key already exists, increment
  redisTemplate.opsForValue().increment(key, usage);
} 
```

That way you're guaranteed every entry added to redis has its expiration properly set. It's an extra call to Redis, but in this case seems necessary.

### PR DESCRIPTION
**Pull request by vasilaio**
Fixes #162

#### Changes proposed in this pull request:
As suggested by @alowrey, I replaced the  increment + expire commands with setIfAbsent + increment.

### CODE REVIEW

File: spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java [hunk 1]
```diff
@@ -62,26 +62,19 @@ protected void calcRemainingQuota(final Long quota, final Long refreshInterval,
...
-            // Redis returns the value of key after the increment, check for the first increment, and the expiration time is set
-            if (current != null && current.equals(usage)) {
-                handleExpiration(key, refreshInterval);
+            Long current = 0L;
+            Boolean present = this.redisTemplate.opsForValue().setIfAbsent(key, usage, refreshInterval, SECONDS);
+            if (Boolean.FALSE.equals(present)) {
+                // Key already exists, increment
+              current = this.redisTemplate.opsForValue().increment(key, usage);
             }
+            return Math.max(-1, limit - (current != null ? current : 0L));
```
Comment (marcosbarbero) [inline spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java]: I was thinking, maybe we instead of adding this line in here we could just replace the `return limit;` with
```
return Math.max(-1, limit - (current != null ? current : 0L));
```

WDYT?

Comment (vasilaio) [reply spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java]: I agree that it is better to have a single return place, but unfortunately I deleted my local branch for this PR and I don't know if I can update the code. If you create a separate branch for this commit I will change the code.

Comment (marcosbarbero) [reply spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java]: You can check out this PR locally. This guide may be helpful for you https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

Comment (vasilaio) [reply spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java]: Thank you for the guide, but I can't push to this PR or create a new branch on your repo. I can created another PR just for this change.  Is this ok?

Comment (marcosbarbero) [reply spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java]: That's also fine :)
